# Generated by Django 5.1.1 on 2024-10-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="palette",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_palette",
                to="profiles.palette",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="text_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_text_color",
                to="profiles.color",
            ),
        ),
    ]
