# Generated by Django 5.1.1 on 2024-10-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_palette_alter_profile_text_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palette",
            name="primary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_palette",
                to="profiles.color",
            ),
        ),
        migrations.AlterField(
            model_name="palette",
            name="secondary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_palette",
                to="profiles.color",
            ),
        ),
        migrations.AlterField(
            model_name="palette",
            name="third",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="third_palette",
                to="profiles.color",
            ),
        ),
    ]
