# Generated by Django 5.1.1 on 2024-10-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_palette_primary_alter_palette_secondary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="palette",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="text_color",
        ),
        migrations.AddField(
            model_name="uisetting",
            name="text_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_text_color",
                to="profiles.color",
            ),
        ),
        migrations.AlterField(
            model_name="uisetting",
            name="palette",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_palette",
                to="profiles.palette",
            ),
        ),
    ]
