# Generated by Django 5.1.1 on 2024-10-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_profile_palette_remove_profile_text_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uisetting",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="ui_settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="profiles.uisetting",
            ),
        ),
    ]
