# Generated by Django 5.1.1 on 2024-10-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SimpleTodoList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("refresh_interval", models.PositiveIntegerField(default=60)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="widgets_icons/")),
                ("position", models.CharField(blank=True, max_length=40, null=True)),
                ("resizable", models.BooleanField(default=True)),
                ("size", models.CharField(default="medium", max_length=40)),
                ("min_height", models.IntegerField(default=100)),
                ("max_height", models.IntegerField(default=600)),
                ("min_width", models.IntegerField(default=100)),
                ("max_width", models.IntegerField(default=400)),
                ("color", models.CharField(default="beige", max_length=40)),
                ("border_color", models.CharField(default="black", max_length=40)),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="widgets", to="dashboard.dashboard"
                    ),
                ),
                ("tasks", models.ManyToManyField(related_name="todo_lists", to="widgets.task")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
