# Generated by Django 5.1.1 on 2024-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpletodolist",
            name="title",
        ),
        migrations.AlterField(
            model_name="simpletodolist",
            name="name",
            field=models.CharField(default="Widget", max_length=128),
        ),
    ]
