# Generated by Django 5.1.1 on 2024-10-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_palette_primary_alter_palette_secondary_and_more"),
        ("widgets", "0002_remove_simpletodolist_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpletodolist",
            name="border_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="widget_border_color",
                to="profiles.color",
            ),
        ),
        migrations.AlterField(
            model_name="simpletodolist",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="widget_background",
                to="profiles.color",
            ),
        ),
    ]
