# Generated by Django 5.1.1 on 2024-10-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_palette_primary_alter_palette_secondary_and_more"),
        ("widgets", "0003_alter_simpletodolist_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpletodolist",
            name="text_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="widget_text_color",
                to="profiles.color",
            ),
        ),
    ]
