# Generated by Django 5.1.1 on 2024-10-11 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0004_simpletodolist_text_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpletodolist",
            name="progress_bar",
            field=models.PositiveIntegerField(
                default=100,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
