# Generated by Django 5.1.1 on 2024-10-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("profiles", "0003_alter_palette_primary_alter_palette_secondary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="background_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard",
                to="profiles.color",
            ),
        ),
    ]
